name: Scheduled Sentiment Analysis

on:
  schedule:
    - cron: '0 0 * * 0'  # This cron expression means the workflow will run every Sunday at midnight UTC

jobs:
  analyze_sentiments:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install supabase
          pip install vaderSentiment

      - name: Run Scheduled Sentiment Analysis
        run: python sentiment-analysis/your_script.py  # Update this with the correct path to your script
